#!/usr/bin/env python3
"""Verify that every declaration cited with \\lean{...} in the blueprint really
exists in the compiled Lean project.

Extracts the names from blueprint/src/content.tex (following \\input), writes
blueprint/CheckDecls.lean with one `#check @name` per declaration, and runs it
through `lake env lean`.  Exits nonzero if any name is missing, which is the
guard against the blueprint drifting away from the Lean sources.
"""
import re
import subprocess
import sys
from pathlib import Path

root = Path(__file__).resolve().parent      # blueprint/
project = root.parent                       # repository root


def strip_comments(text: str) -> str:
    """Drop TeX comments, so the conventions note at the top of content.tex
    does not get mistaken for a real citation."""
    out = []
    for line in text.splitlines():
        cut = None
        for i, ch in enumerate(line):
            if ch == "%" and (i == 0 or line[i - 1] != "\\"):
                cut = i
                break
        out.append(line if cut is None else line[:cut])
    return "\n".join(out)


def read_with_inputs(path: Path) -> str:
    """Read a .tex file, splicing in any file it pulls with \\input{...}."""
    text = strip_comments(path.read_text(encoding="utf-8"))
    for name in re.findall(r"\\input\{([^}]*)\}", text):
        child = path.parent / (name if name.endswith(".tex") else name + ".tex")
        if child.exists():
            text += "\n" + read_with_inputs(child)
    return text


content = read_with_inputs(root / "src" / "content.tex")

names = []
for group in re.findall(r"\\lean\{([^}]*)\}", content):
    for name in group.split(","):
        name = name.strip()
        if name and name not in names:
            names.append(name)

if not names:
    sys.exit("No \\lean{...} declarations found in content.tex")

checks = "\n".join(f"#check @{n}" for n in names)
(root / "CheckDecls.lean").write_text(
    f"import MorseFloer\n\n-- generated by checkdecls.py; do not edit\n{checks}\n",
    encoding="utf-8")

print(f"Checking {len(names)} declarations cited in the blueprint...")
res = subprocess.run(
    ["lake", "env", "lean", str(root / "CheckDecls.lean")],
    cwd=project, capture_output=True, text=True)
errors = [l for l in res.stdout.splitlines() + res.stderr.splitlines()
          if "error" in l.lower()]
if res.returncode != 0 or errors:
    print("\n".join(errors) or res.stdout[-2000:])
    sys.exit(f"FAILED: some of the {len(names)} declarations are missing.")
print(f"OK: all {len(names)} declarations exist in the compiled project.")
