#!/usr/bin/env python3
"""Point the blueprint's Lean links at local, browsable copies of the sources.

leanblueprint links every \\lean{...} declaration to the online Mathlib
documentation, which does not know the declarations of this project, so the
links land on a 404 page.  This script

* asks Lean for the module and line of every cited declaration,
* renders each Lean source file of the project as an HTML page with an anchor
  per line (blueprint/web/lean/<Module/Path>.html#L<line>), and
* rewrites the links in blueprint/web/*.html to those pages.

Declarations outside the project (Mathlib's) keep their online link.
Run after plasTeX (`make blueprint-web` does).
"""
import html
import re
import subprocess
import sys
from pathlib import Path

root = Path(__file__).resolve().parent      # blueprint/
project = root.parent                       # repository root
web = root / "web"
DOCS = "https://leanprover-community.github.io/mathlib4_docs/find/#doc/"

sys.path.insert(0, str(root))


def cited_names():
    """The declarations cited with \\lean{...}, as checkdecls.py collects them."""
    src = root / "src" / "content.tex"

    def strip(text):
        out = []
        for line in text.splitlines():
            cut = None
            for i, ch in enumerate(line):
                if ch == "%" and (i == 0 or line[i - 1] != "\\"):
                    cut = i
                    break
            out.append(line if cut is None else line[:cut])
        return "\n".join(out)

    def read(path):
        text = strip(path.read_text(encoding="utf-8"))
        for name in re.findall(r"\\input\{([^}]*)\}", text):
            child = path.parent / (name if name.endswith(".tex") else name + ".tex")
            if child.exists():
                text += "\n" + read(child)
        return text

    names = []
    for group in re.findall(r"\\lean\{([^}]*)\}", read(src)):
        for name in group.split(","):
            name = name.strip()
            if name and name not in names:
                names.append(name)
    return names


def locate(names):
    """Module and line of each declaration, from the compiled project."""
    lean = root / "DeclLocs.lean"
    items = ", ".join(f'"{n}"' for n in names)
    lean.write_text(f"""import MorseFloer
open Lean Elab Command

-- generated by link_decls.py; do not edit
#eval show CommandElabM Unit from do
  let env ← getEnv
  for s in [{items}] do
    let n := s.toName
    match env.getModuleIdxFor? n with
    | none => IO.println s!"LOC|{{s}}||0"
    | some idx =>
      let mod := env.header.moduleNames[idx.toNat]!
      let line := (← findDeclarationRanges? n).map (·.range.pos.line) |>.getD 0
      IO.println s!"LOC|{{s}}|{{mod}}|{{line}}"
""", encoding="utf-8")
    out = subprocess.run(["lake", "env", "lean", str(lean)], cwd=project,
                         capture_output=True, text=True)
    locs = {}
    for line in out.stdout.splitlines():
        if line.startswith("LOC|"):
            _, name, mod, ln = line.split("|")
            if mod:
                locs[name] = (mod, int(ln))
    if not locs:
        sys.exit("link_decls.py: Lean returned no locations\n" + out.stderr[-2000:])
    return locs


PAGE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>
body {{ margin: 0; font-family: ui-monospace, Menlo, monospace; font-size: 13px;
       background: #fdfdfd; color: #222; }}
header {{ padding: 8px 16px; background: #f0f0f0; border-bottom: 1px solid #ddd;
         font-family: system-ui, sans-serif; }}
header a {{ color: #0366d6; }}
table {{ border-collapse: collapse; }}
td.n {{ color: #999; text-align: right; padding: 0 12px 0 16px; user-select: none;
       vertical-align: top; }}
td.n a {{ color: inherit; text-decoration: none; }}
td.c {{ white-space: pre; padding-right: 16px; }}
tr:target {{ background: #fff3b0; }}
@media (prefers-color-scheme: dark) {{
  body {{ background: #1e1e1e; color: #ddd; }} header {{ background: #2a2a2a; border-color: #444; }}
  tr:target {{ background: #4a4420; }} td.n {{ color: #777; }}
}}
</style></head><body>
<header><a href="{up}index.html">Blueprint</a> · <code>{title}</code></header>
<table>
{rows}
</table></body></html>
"""


def render_sources(modules):
    """One HTML page per Lean file, with an anchor per line."""
    for mod in modules:
        src = project / (mod.replace(".", "/") + ".lean")
        if not src.exists():
            continue
        dest = web / "lean" / (mod.replace(".", "/") + ".html")
        dest.parent.mkdir(parents=True, exist_ok=True)
        rows = "\n".join(
            f'<tr id="L{i}"><td class="n"><a href="#L{i}">{i}</a></td>'
            f'<td class="c">{html.escape(text)}</td></tr>'
            for i, text in enumerate(src.read_text(encoding="utf-8").splitlines(), 1))
        up = "../" * (len(mod.split(".")) )
        dest.write_text(PAGE.format(title=html.escape(src.relative_to(project).as_posix()),
                                    up=up, rows=rows), encoding="utf-8")


def rewrite_links(locs):
    """Replace the online doc links of project declarations by local ones."""
    pat = re.compile(re.escape(DOCS) + r"([^\"<>\s]+)")
    changed = 0
    for page in web.glob("*.html"):
        text = page.read_text(encoding="utf-8")

        def sub(m):
            name = html.unescape(m.group(1))
            if name in locs:
                mod, line = locs[name]
                return f"lean/{mod.replace('.', '/')}.html#L{line}"
            return m.group(0)

        new = pat.sub(sub, text)
        if new != text:
            page.write_text(new, encoding="utf-8")
            changed += 1
    return changed


def install_fixes():
    """Copy blueprint_fixes.js into the site and load it on every page."""
    js = web / "js"
    js.mkdir(exist_ok=True)
    (js / "blueprint_fixes.js").write_text(
        (root / "src" / "blueprint_fixes.js").read_text(encoding="utf-8"), encoding="utf-8")
    tag = '<script type="text/javascript" src="js/blueprint_fixes.js"></script>'
    for page in web.glob("*.html"):
        text = page.read_text(encoding="utf-8")
        if tag not in text and "</body>" in text:
            page.write_text(text.replace("</body>", tag + "\n</body>", 1), encoding="utf-8")


def main():
    install_fixes()
    names = cited_names()
    locs = locate(names)
    project_locs = {n: v for n, v in locs.items() if v[0].startswith("MorseFloer")}
    render_sources({mod for mod, _ in project_locs.values()})
    pages = rewrite_links(project_locs)
    print(f"link_decls.py: {len(project_locs)} of {len(names)} declarations linked locally "
          f"({len(names) - len(project_locs)} left to the Mathlib docs); {pages} pages rewritten.")


if __name__ == "__main__":
    main()
