import MorseFloer.Part1.Ch3
import MorseFloer.Part2.Ch8

/-!
# Chapter 11: Floer homology, invariance

Formalization of Chapter 11 of Audin–Damian, *Théorie de Morse et homologie de
Floer* (Part II, printed pages 347–412).

Chapter 10 identifies `HF⋆(H, J)` with the Morse homology of `W` for one
particular pair.  This chapter closes the circle: it proves that `HF⋆(H, J)`
does not depend on the regular pair `(H, J)` at all, and with that the Arnold
conjecture is proved (§11.6).

The argument copies §3.4 of Part I.  Given two regular pairs `(Ha, Ja)` and
`(Hb, Jb)`, one chooses a smooth homotopy `Γ = (H, J)` from the first to the
second which is *stationary* outside a compact interval `[-R, R]` of the
`s`-variable, and studies the **parametrised Floer equation**

`∂u/∂s + J_s(u) (∂u/∂t − X_{s,t}(u)) = 0`.

Its finite-energy solutions run from a `1`-periodic orbit of `Ha` to one of
`Hb` (Theorem 11.1.1).  Counting the `0`-dimensional pieces of these spaces
modulo `2` defines

`Φ_Γ : CF⋆(Ha, Ja) → CF⋆(Hb, Jb)`,

a morphism of complexes (§11.1.c) which is the identity for the stationary
homotopy (Proposition 11.1.14).  Two homotopies between the same pairs give
chain-homotopic morphisms (Proposition 11.2.8, proved in §11.3), and the
concatenation of two homotopies induces the composite morphism in homology
(Proposition 11.2.9, proved in §11.5).  Taking `(Hc, Jc) = (Ha, Ja)` and the
stationary homotopy makes `Φ_Γ` an isomorphism on homology.

## What this file contains

Chapters 6, 7, 9 and 10 are being formalized separately and are **not** imported
here; as in `MorseFloer.Part2.Ch8`, everything the Floer analysis provides is
taken as explicit hypotheses or as abstract parameters.  A later pass must
connect the predicates below to Chapter 6's Floer operator, Chapter 7's
Conley–Zehnder index and Chapter 9's spaces of trajectories.

**The homological algebra of the invariance proof is formalized completely, and
it is the logical skeleton of the chapter.**  Over an arbitrary commutative ring
`R` and for `ℤ`-graded chain groups `CF_k` freely generated by the orbits of
Conley–Zehnder index `k`:

* `transfer` — the linear map attached to a "count matrix" between two sets of
  orbits.  Both the Floer differential `∂` (`dLin`) and the morphism `Φ_Γ` are
  instances of it, so all three identities of the chapter (`∂ ∘ ∂ = 0`, the
  chain-map property, the chain-homotopy identity) reduce to one computation
  with a double sum, `transfer_comp_apply`.
* `ChainMapPairs` — the hypothesis that the once-broken parametrised
  trajectories cancel in pairs.  It is the conclusion of Theorem 11.1.15,
  which makes `M_Γ(x,z) ∪ Π_Γ(x,z)` a compact `1`-manifold with boundary
  `Π_Γ(x,z)`; the boundary of such a manifold has an even number of points.
  From it, `transfer_chainMap` **proves** `Φ_Γ ∘ ∂_a = ∂_b ∘ Φ_Γ` (§11.1.c).
* `Hgy` — the homology of a two-term situation `A₀ → A → A₁`, with
  `Hgy.map` (**a chain map induces a map on homology**), `Hgy.map_comp`,
  `Hgy.map_id` and `Hgy.map_eq_of_homotopy` (**chain-homotopic maps agree on
  homology**), all proved.
* `Hgy.map_comp_map_eq_id` — **if `ψ ∘ φ` is chain homotopic to the identity
  then the two induced maps on homology are mutually inverse in one direction**;
  applied twice this gives `floerHomologyEquiv`, the isomorphism
  `HF_k(Ha, Ja) ≅ HF_k(Hb, Jb)` of §11.6, which is proved outright from the
  chapter's geometric input.
* `transfer_idCount` is **Proposition 11.1.14** (`Φ_Id = Id`), and
  `transfer_comp_concat` is the chain-level content of **Proposition 11.5.3**
  (the concatenated homotopy `Γ_ρ` counts exactly the composable pairs, so
  `Φ_{Γ_ρ} = Φ_{Γ''} ∘ Φ_{Γ'}`).

Two purely combinatorial results of §11.1.c are also proved in full:
**Corollary 11.1.11** (`index_drop_ge`, the bound `μ(x) − μ(y) ≥ k + ℓ` on the
number of breakings, a telescoping sum) and **Corollary 11.1.13**
(`no_breaking_of_index_eq`: when `μ(x) = μ(y)` no breaking can occur, so
`M_Γ(x,y)` is compact).  **Corollary 11.1.3** (`exists_energy_bound`, a uniform
energy bound from Proposition 11.1.2 and the finiteness of the set of critical
points) is proved as well, and so is **Lemma 11.1.9** in the form in which it is
used: a continuous functional annihilating a dense family of perturbation
gradients vanishes.

## Gaps: the analysis of §11.1.a–b and §§11.2, 11.4

Mathlib has no Sobolev spaces, no `C^∞_loc` topology, no moduli spaces and no
manifolds with boundary, so the analytic core of the chapter is out of reach.
Following `MorseFloer.Part2.Ch8`, a statement that would be **false** of
arbitrary abstract data is recorded as a *predicate* the data may satisfy, not
as a `sorry`ed theorem:

* the parametrised Floer equation itself *is* statable in the local model
  (`IsFloerSolution`, `IsFloerHomotopy`, `energy`), and so are the finite-energy
  condition and the space `M_Γ` (`floerTrajectories`);
* **Theorem 11.1.1** (finite energy forces convergence to `1`-periodic orbits at
  `s → ∓∞`) is the predicate `HasAsymptoticEnds`.  It is false without the
  compactness of `W` and the nondegeneracy of the orbits, neither of which the
  local model records.
* **Proposition 11.1.2** (`E(u) ≤ A_{Ha}(x) − A_{Hb}(y) + k`) is the predicate
  `HasEnergyEstimate`; the action functional `A_H` needs Chapter 6.
* **Theorem 11.1.4** (`M_Γ` is compact for `C^∞_loc`) is `IsLocUnifCompact`,
  which records only the `C⁰_loc` statement — Mathlib has
  `TendstoLocallyUniformly` but no topology of `C^∞` convergence.
* **Proposition 11.1.5** (uniform bound on the gradient of `u`) is
  `HasUniformGradientBound`.
* **Theorems 11.1.6 and 11.1.7** are the predicates `HomotopyData.IsRegular`,
  `HomotopyData.IsGenericallyRegular`, `HomotopyData.IsFredholmData` and
  `HomotopyData.HasCZIndex` on a `HomotopyData` — the parametrised analogue of
  Chapter 8's `FloerData`.  What survives of Theorem 11.1.6 is proved:
  `finrank_ker_eq_cz_sub_cz` (the tangent space to `M_Γ(x,y)` has dimension
  `μ(x) − μ(y)`, note the absence of the `−1` of Chapter 9, since the
  parametrised equation has no translation symmetry) and `dense_regularSet`
  (Baire: regular homotopies are dense).
* **Proposition 11.1.8** (surjectivity of `Γ(Y,h) = (dF_Γ)_u Y + grad_u h`) is
  `IsTransverseHomotopy`; Chapter 8's `gammaOp` is reused, and
  `Chapter8.gammaOp_surjective_iff` already says that it is equivalent to the
  two ranges spanning.
* **Theorem 11.1.10** (convergence to broken trajectories) is `HasBrokenLimits`
  and **Lemma 11.1.12** is `HasTranslationLimits`.
* **Theorem 11.1.15** (`M_Γ(x,z) ∪ Π_Γ(x,z)` is a compact `1`-manifold with
  boundary `Π_Γ(x,z)`) has **no Lean statement**: there is no moduli space and
  no manifold with boundary to speak of.  Its consequence is the hypothesis
  `ChainMapPairs`.
* **Theorem 11.1.16** and the whole of **§11.2** (the gluing construction: the
  pre-gluing `u #_ρ v`, the Newton–Picard scheme, Propositions 11.2.1–11.2.4,
  Lemmas 11.2.5–11.2.7) have no Lean statement.  They are estimates in
  `W^{1,p}` and `L^p` for the operator `F^ρ`.
* **§11.3** (Theorems 11.3.2, 11.3.3, 11.3.7, 11.3.10, 11.3.11, Propositions
  11.3.4, 11.3.5, 11.3.8, Lemmas 11.3.6, 11.3.9, Remarks 11.3.1, 11.3.12,
  11.3.13) is the same package for a homotopy of homotopies `(Γ_λ)`; only its
  chain-level conclusion is recorded, as `ChainHomotopyPairs` and
  **Proposition 11.2.8** (`transfer_homotopy`, proved).  Theorem 11.3.14 and the
  whole of **§11.4** are the corresponding gluing theorem and have no statement.
* **§11.5**: Lemma 11.5.1 (a small perturbation makes `Γ_ρ` regular),
  Proposition 11.5.2, and Propositions 11.5.4–11.5.13 (the injectivity and
  surjectivity of the gluing map `χ_ρ`) have no Lean statement.  Their
  conclusion, **Proposition 11.5.3**, is recorded as `IsConcatenation`, and the
  chain-level identity it yields is proved (`transfer_comp_concat`).

## Conventions

The book works modulo `2`; nothing below needs that, so the chain groups are
over an arbitrary commutative ring `R` and the chain-homotopy identity is
written `Φ_{Γ₁} − Φ_{Γ₀} = S ∘ ∂_a + ∂_b ∘ S`, which over `Z/2` is the book's
`Φ_{Γ₁} + Φ_{Γ₀} = S ∘ ∂_a + ∂_b ∘ S`.  The grading is by the Conley–Zehnder
index and is therefore by `ℤ`, not by `ℕ` as in Part I.
-/

open Filter Topology MeasureTheory
open scoped ContDiff

namespace MorseFloer
namespace Chapter11

/-! ## §11.1.a The parametrised Floer equation

The equation, the energy and the space `M_Γ` are written in the local model: `W`
is replaced by a normed space `V`, the circle `S¹` by `ℝ` together with
`1`-periodicity, `J_s` by a family of endomorphisms of `V` and the Hamiltonian
vector field `X_{s,t}` (the symplectic dual of `dH_{s,t}`) by a family of vector
fields.  This is the convention of the whole project: the book's proofs live in
a chart. -/

section Parametrized

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-- A `1`-periodic trajectory of the time-dependent vector field `X`: the
critical points of the action functional `A_H` (§6.3). -/
def IsPeriodicOrbit (X : ℝ → V → V) (x : ℝ → V) : Prop :=
  (∀ t, HasDerivAt x (X t (x t)) t) ∧ ∀ t, x (t + 1) = x t

/-- **A homotopy `Γ` from `(Ha, Ja)` to `(Hb, Jb)`** (§11.1, opening page).

The data is a family `(H_{s,t}, J_s)` which is stationary equal to `(Ha, Ja)` for
`s ≤ −R` and to `(Hb, Jb)` for `s ≥ R`.  Such homotopies exist because the space
of calibrated almost complex structures is contractible (Proposition 5.5.6);
that existence statement is not available here, so a homotopy is taken as data.
-/
structure IsFloerHomotopy (R : ℝ) (Ha Hb : ℝ → V → ℝ) (Ja Jb : V → V →L[ℝ] V)
    (H : ℝ → ℝ → V → ℝ) (J : ℝ → V → V →L[ℝ] V) : Prop where
  /-- The interval outside which `Γ` is stationary is nonempty. -/
  radius_pos : 0 < R
  /-- `H(s, ·, ·) = Ha` for `s ≤ −R`. -/
  hamiltonian_atBot : ∀ s ≤ -R, ∀ t p, H s t p = Ha t p
  /-- `H(s, ·, ·) = Hb` for `s ≥ R`. -/
  hamiltonian_atTop : ∀ s, R ≤ s → ∀ t p, H s t p = Hb t p
  /-- `J(s) = Ja` for `s ≤ −R`. -/
  almostComplex_atBot : ∀ s ≤ -R, J s = Ja
  /-- `J(s) = Jb` for `s ≥ R`. -/
  almostComplex_atTop : ∀ s, R ≤ s → J s = Jb

/-- **The parametrised Floer equation** of §11.1.a:

`∂u/∂s + J_s(u) (∂u/∂t − X_{s,t}(u)) = 0`.

Here `X_{s,t}` is the symplectic dual of `dH_{s,t}`; since Chapter 5 records
that symplectic manifolds are not available in Mathlib, the family of
Hamiltonian vector fields is taken as data rather than derived from `H`. -/
def IsFloerSolution (J : ℝ → V → V →L[ℝ] V) (X : ℝ → ℝ → V → V)
    (u : ℝ → ℝ → V) : Prop :=
  ∀ s t : ℝ,
    deriv (fun σ => u σ t) s + J s (u s t) (deriv (fun τ => u s τ) t - X s t (u s t)) = 0

/-- **The energy** `E(u) = ∫∫ ‖∂u/∂s‖²` of §11.1.a.

The norm is the one attached to the metric `ω(·, J_s ·)`, so it depends on `s`;
it enters here as a family `nrm : ℝ → V → ℝ`. -/
noncomputable def energy (nrm : ℝ → V → ℝ) (u : ℝ → ℝ → V) : ℝ :=
  ∫ s : ℝ, ∫ t in (0 : ℝ)..1, (nrm s (deriv (fun σ => u σ t) s)) ^ 2

/-- `E(u) < +∞`: the energy density is integrable in `s`. -/
def HasFiniteEnergy (nrm : ℝ → V → ℝ) (u : ℝ → ℝ → V) : Prop :=
  Integrable fun s : ℝ => ∫ t in (0 : ℝ)..1, (nrm s (deriv (fun σ => u σ t) s)) ^ 2

/-- **The space `M_Γ`** of §11.1.a: the contractible solutions of the
parametrised Floer equation of finite energy.

Contractibility of the loops `u(s, ·)` is a condition on `π₁(W)` and is not
recorded here; `W` is a normed space in the local model, where every loop is
contractible. -/
def floerTrajectories (J : ℝ → V → V →L[ℝ] V) (X : ℝ → ℝ → V → V)
    (nrm : ℝ → V → ℝ) : Set (ℝ → ℝ → V) :=
  {u | (∀ s t, u s (t + 1) = u s t) ∧ IsFloerSolution J X u ∧ HasFiniteEnergy nrm u}

/-- The translated trajectory `u · s`, `(u · s)(σ, t) = u(σ + s, t)`. -/
def translate (s : ℝ) (u : ℝ → ℝ → V) : ℝ → ℝ → V := fun σ t => u (σ + s) t

/-- **Theorem 11.1.1** (parametrised version of Theorem 6.5.6), as a predicate.

Every finite-energy solution of the parametrised Floer equation converges, as
`s → −∞` and as `s → +∞`, to a `1`-periodic orbit of `Xa` and to one of `Xb`
respectively; so `M_Γ` is the union of the spaces `M_Γ(x, y)`.

This is a *predicate on the data*, not a theorem: it is false for an arbitrary
normed space `V`.  The book's proof needs `W` compact, the orbits of `Xa` and
`Xb` nondegenerate, the energy estimate of Proposition 11.1.2 and the
`C^∞_loc` compactness of Theorem 11.1.4, none of which is available. -/
def HasAsymptoticEnds (J : ℝ → V → V →L[ℝ] V) (X : ℝ → ℝ → V → V) (nrm : ℝ → V → ℝ)
    (Xa Xb : ℝ → V → V) : Prop :=
  ∀ u ∈ floerTrajectories J X nrm, ∃ x y : ℝ → V,
    IsPeriodicOrbit Xa x ∧ IsPeriodicOrbit Xb y ∧
      (∀ t, Tendsto (fun s => u s t) atBot (𝓝 (x t))) ∧
      (∀ t, Tendsto (fun s => u s t) atTop (𝓝 (y t)))

/-- The subspace `M_Γ(x, y)` of solutions running from `x` to `y` (§11.1.a). -/
def floerTrajectoriesBetween (J : ℝ → V → V →L[ℝ] V) (X : ℝ → ℝ → V → V)
    (nrm : ℝ → V → ℝ) (x y : ℝ → V) : Set (ℝ → ℝ → V) :=
  {u ∈ floerTrajectories J X nrm |
    (∀ t, Tendsto (fun s => u s t) atBot (𝓝 (x t))) ∧
      ∀ t, Tendsto (fun s => u s t) atTop (𝓝 (y t))}

/-- **Proposition 11.1.2**, as a predicate: there is a constant `k`, namely the
supremum of `|∂H/∂s|` over `[-R, R] × S¹ × W`, such that every solution running
from `x` to `y` has energy at most `A_{Ha}(x) − A_{Hb}(y) + k`.

The proof is a Stokes computation with the action functional `A_H` of §6.3
(`E(u) = ∫ u⋆ω − dH(∂u/∂s)`, then a primitive on a filling disc).  The action
functional needs the symplectic form, so it enters here as abstract data
`actA`, `actB`, and `ends u` records the pair of limits supplied by Theorem
11.1.1. -/
def HasEnergyEstimate (nrm : ℝ → V → ℝ) (S : Set (ℝ → ℝ → V))
    (actA actB : (ℝ → V) → ℝ) (ends : (ℝ → ℝ → V) → (ℝ → V) × (ℝ → V)) : Prop :=
  ∃ k : ℝ, ∀ u ∈ S, energy nrm u ≤ actA (ends u).1 - actB (ends u).2 + k

/-- **Corollary 11.1.3**: the energy of the solutions in `M_Γ` is uniformly
bounded.

This is *proved*: the book deduces it from Proposition 11.1.2 and the finiteness
of `Crit A_{Ha}` and `Crit A_{Hb}`, and that deduction is exactly the statement
that a family of reals bounded above by the values of a function on a finite
type is bounded.  Here `ι` stands for the finite set of pairs of critical points
and `b` for `(x, y) ↦ A_{Ha}(x) − A_{Hb}(y) + k`. -/
theorem exists_energy_bound {α ι : Type*} [Finite ι] (E : α → ℝ) (S : Set α) (b : ι → ℝ)
    (h : ∀ u ∈ S, ∃ i, E u ≤ b i) : ∃ C : ℝ, ∀ u ∈ S, E u ≤ C := by
  obtain ⟨C, hC⟩ := (Set.finite_range b).bddAbove
  refine ⟨C, fun u hu => ?_⟩
  obtain ⟨i, hi⟩ := h u hu
  exact hi.trans (hC ⟨i, rfl⟩)

/-- **Theorem 11.1.4**, as a predicate: `M_Γ` is compact for the `C^∞_loc`
topology.

Only the `C⁰_loc` half of the statement is expressible: Mathlib has
`TendstoLocallyUniformly` but no topology of locally uniform convergence of all
derivatives.  The book's proof is Ascoli (from the gradient bound of
Proposition 11.1.5, itself a consequence of Corollary 11.1.3) followed by
elliptic regularity (Proposition 6.5.3), which upgrades `C⁰_loc` convergence to
`C^∞_loc` convergence; elliptic regularity is the subject of Chapter 12 and is
not available. -/
def IsLocUnifCompact (S : Set (ℝ → ℝ → V)) : Prop :=
  ∀ u : ℕ → ℝ → ℝ → V, (∀ n, u n ∈ S) →
    ∃ φ : ℕ → ℕ, StrictMono φ ∧ ∃ v ∈ S,
      TendstoLocallyUniformly (fun n (p : ℝ × ℝ) => u (φ n) p.1 p.2)
        (fun p : ℝ × ℝ => v p.1 p.2) atTop

/-- **Proposition 11.1.5**, as a predicate: the gradients of the elements of
`M_Γ` are uniformly bounded.

The book argues by contradiction: an unbounded sequence of gradients produces,
after rescaling, a nonconstant `J`-holomorphic plane of finite energy, which the
isoperimetric argument of Lemma 6.6.5 forbids.  Neither the bubbling analysis
nor the metrics `g_s = ω(·, J_s ·)` are available. -/
def HasUniformGradientBound (S : Set (ℝ → ℝ → V)) : Prop :=
  ∃ A > 0, ∀ u ∈ S, ∀ s t : ℝ,
    ‖fderiv ℝ (fun p : ℝ × ℝ => u p.1 p.2) (s, t)‖ ≤ A

/-- **Lemma 11.1.12**, as a predicate: along a sequence of translations
`s_n → +∞` (resp. `−∞`) a sequence of elements of `M_Γ(x, y)` subconverges to a
solution of the *unparametrised* Floer equation for `(Hb, Jb)` (resp.
`(Ha, Ja)`).

The point is that `Γ` is stationary for `|s| ≥ R`, so on every compact set the
translated equation is eventually the unparametrised one.  The proof is Ascoli
plus elliptic regularity, as for Theorem 11.1.4. -/
def HasTranslationLimits (Sa Sb SG : Set (ℝ → ℝ → V)) : Prop :=
  ∀ un : ℕ → ℝ → ℝ → V, (∀ n, un n ∈ SG) → ∀ sn : ℕ → ℝ,
    (Tendsto sn atTop atTop → ∃ φ : ℕ → ℕ, StrictMono φ ∧ ∃ v ∈ Sb,
        TendstoLocallyUniformly
          (fun n (p : ℝ × ℝ) => translate (sn (φ n)) (un (φ n)) p.1 p.2)
          (fun p : ℝ × ℝ => v p.1 p.2) atTop) ∧
    (Tendsto sn atTop atBot → ∃ φ : ℕ → ℕ, StrictMono φ ∧ ∃ w ∈ Sa,
        TendstoLocallyUniformly
          (fun n (p : ℝ × ℝ) => translate (sn (φ n)) (un (φ n)) p.1 p.2)
          (fun p : ℝ × ℝ => w p.1 p.2) atTop)

/-- **Theorem 11.1.10**, as a predicate: a sequence in `M_Γ(x, y)` subconverges
to a concatenation of a broken trajectory for `(Ha, Ja)`, exactly one element of
`M_Γ`, and a broken trajectory for `(Hb, Jb)`.

The `k` translations `s_n^i → −∞` produce the pieces `u_i ∈ M_{(Ha,Ja)}`, the
`ℓ` translations `s_n'^j → +∞` produce the pieces `v_j ∈ M_{(Hb,Jb)}`, and the
untranslated sequence converges to `w ∈ M_Γ`.  The bookkeeping of *which*
critical points the pieces join is what Corollary 11.1.11 below uses; it is
recorded there as an arithmetic statement, because there is no space `M(x,y)`
here to index by.  The proof of the theorem is Theorem 11.1.4, Lemma 11.1.12 and
the exit-time argument of Corollary 9.1.8. -/
def HasBrokenLimits (Sa Sb SG : Set (ℝ → ℝ → V)) : Prop :=
  ∀ un : ℕ → ℝ → ℝ → V, (∀ n, un n ∈ SG) →
    ∃ φ : ℕ → ℕ, StrictMono φ ∧
      ∃ (k l : ℕ) (sn : Fin k → ℕ → ℝ) (sn' : Fin l → ℕ → ℝ)
        (ui : Fin k → ℝ → ℝ → V) (vj : Fin l → ℝ → ℝ → V) (w : ℝ → ℝ → V),
        (∀ i, Tendsto (sn i) atTop atBot) ∧ (∀ j, Tendsto (sn' j) atTop atTop) ∧
        (∀ i, ui i ∈ Sa) ∧ (∀ j, vj j ∈ Sb) ∧ w ∈ SG ∧
        (∀ i, TendstoLocallyUniformly
            (fun n (p : ℝ × ℝ) => translate (sn i (φ n)) (un (φ n)) p.1 p.2)
            (fun p : ℝ × ℝ => ui i p.1 p.2) atTop) ∧
        (∀ j, TendstoLocallyUniformly
            (fun n (p : ℝ × ℝ) => translate (sn' j (φ n)) (un (φ n)) p.1 p.2)
            (fun p : ℝ × ℝ => vj j p.1 p.2) atTop) ∧
        TendstoLocallyUniformly (fun n (p : ℝ × ℝ) => un (φ n) p.1 p.2)
          (fun p : ℝ × ℝ => w p.1 p.2) atTop

end Parametrized

/-! ### Corollaries 11.1.11 and 11.1.13: how many breakings can occur

These two corollaries of Theorem 11.1.10 are pure bookkeeping with the
Conley–Zehnder index, and they are proved here in full.  In the limit
configuration of Theorem 11.1.10 the indices satisfy

`μ(xᵢ) − μ(xᵢ₊₁) ≥ 1`, `μ(yⱼ) − μ(yⱼ₊₁) ≥ 1` (Theorem 8.1.2 and §9.1.a),
`μ(x_k) ≥ μ(y₀)` (Theorem 11.1.6),

since a moduli space of negative dimension is empty.  Summing gives the bound. -/

section IndexCount

/-- Telescoping: if each step drops the index by at least one, then `n` steps
drop it by at least `n`. -/
theorem le_of_index_steps (a : ℕ → ℤ) (n : ℕ) (h : ∀ i < n, a (i + 1) + 1 ≤ a i) :
    a n + (n : ℤ) ≤ a 0 := by
  induction n with
  | zero => simp
  | succ m ih =>
    have h1 : a (m + 1) + 1 ≤ a m := h m (Nat.lt_succ_self m)
    have h2 : a m + (m : ℤ) ≤ a 0 := ih fun i hi => h i (by omega)
    push_cast
    omega

/-- **Corollary 11.1.11.**  In the limit configuration of Theorem 11.1.10 the
total number `k + ℓ` of breakings is at most the index drop `μ(x) − μ(y)`.

Here `a i = μ(xᵢ)` and `b j = μ(yⱼ)`; `ha` and `hb` say that each unparametrised
piece drops the index by at least one and `hab` says that the parametrised piece
does not raise it. -/
theorem index_drop_ge {k l : ℕ} (a b : ℕ → ℤ)
    (ha : ∀ i < k, a (i + 1) + 1 ≤ a i) (hb : ∀ j < l, b (j + 1) + 1 ≤ b j)
    (hab : b 0 ≤ a k) : (k : ℤ) + (l : ℤ) ≤ a 0 - b l := by
  have h1 := le_of_index_steps a k ha
  have h2 := le_of_index_steps b l hb
  omega

/-- **Corollary 11.1.13.**  If `μ(x) = μ(y)` then no breaking can occur, so no
sequence of `M_Γ(x, y)` can converge to a broken trajectory and `M_Γ(x, y)` is
compact — a finite set of points, since it is a `0`-dimensional manifold by
Theorem 11.1.6.  This is what makes the count `n_Γ(x, y)` of §11.1.c well
defined. -/
theorem no_breaking_of_index_eq {k l : ℕ} (a b : ℕ → ℤ)
    (ha : ∀ i < k, a (i + 1) + 1 ≤ a i) (hb : ∀ j < l, b (j + 1) + 1 ≤ b j)
    (hab : b 0 ≤ a k) (hidx : a 0 = b l) : k = 0 ∧ l = 0 := by
  have h := index_drop_ge a b ha hb hab
  omega

end IndexCount

/-! ## §11.1.b Transversality for the parametrised equation

The chapter reruns Chapter 8 for the parametrised equation, with the pleasant
simplification that the perturbations `h : ℝ × S¹ × W → ℝ` are now allowed to
depend on `s`: the source space of the transversality operator is bigger, so
surjectivity is easier, and the unique-continuation theory of §8.6 is not
needed.

The data is the parametrised analogue of `MorseFloer.Chapter8.FloerData`: two
Floer data `Da`, `Db` for the two ends, together with the spaces `M_Γ(x, y)` and
the linearised operator `(dF_Γ)_u`. -/

section Transversality

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F]

/-- **The abstract data attached to a homotopy `Γ`.**

`Sol x y` stands for `M_Γ(x, y)`, the space of solutions of the parametrised
Floer equation running from the orbit `x` of `Ha` to the orbit `y` of `Hb`, and
`lin u` for the linearised operator `(dF_Γ)_u` read in a unitary trivialisation
along `u`, an operator `W^{1,p}(u⋆TW) → L^p(u⋆TW)` — here the fixed model spaces
`E` and `F` of Chapter 8.

A later pass must connect this to Chapter 6's Floer operator. -/
structure HomotopyData (Da Db : Chapter8.FloerData E F) where
  /-- `M_Γ(x, y)`, the solutions of the parametrised equation from `x` to `y`. -/
  Sol : Da.Orbit → Db.Orbit → Type
  /-- The linearised operator `(dF_Γ)_u`. -/
  lin : ∀ {x : Da.Orbit} {y : Db.Orbit}, Sol x y → (E →L[ℝ] F)

namespace HomotopyData

variable {Da Db : Chapter8.FloerData E F} (G : HomotopyData Da Db)

/-- **A regular homotopy** (§11.1.b, the conclusion of Theorem 11.1.6): the
linearised operator `(dF_Γ)_u` is surjective at every solution.  This is the
transversality of the section `σ` to the zero section. -/
def IsRegular : Prop :=
  ∀ (x : Da.Orbit) (y : Db.Orbit) (u : G.Sol x y), Function.Surjective (G.lin u)

/-- The Fredholm half of **Theorem 11.1.7**: `(dF_Γ)_u` is a Fredholm operator.

Assumed here.  The book's proof is the one of Theorem 8.1.5: since `Γ` is
stationary for `|s| ≥ R`, in a unitary frame along `u` the operator is again
`∂̄ + S(s,t)` with `S(s,t)` converging to symmetric matrices as `s → ±∞`. -/
def IsFredholmData : Prop :=
  ∀ (x : Da.Orbit) (y : Db.Orbit) (u : G.Sol x y),
    ContinuousLinearMap.IsFredholm (G.lin u)

/-- The index half of **Theorem 11.1.7**: the index of `(dF_Γ)_u` is
`μ(x) − μ(y)`.

Note the absence of the `−1` of Chapter 9: the parametrised equation is *not*
invariant under translation in `s`, so `M_Γ(x,y)` has dimension `μ(x) − μ(y)`
and not `μ(x) − μ(y) − 1`.  This is why `Φ_Γ` preserves the degree while `∂`
lowers it. -/
def HasCZIndex : Prop :=
  ∀ (x : Da.Orbit) (y : Db.Orbit) (u : G.Sol x y),
    Chapter16.fredholmIndex (G.lin u) = Da.cz x - Db.cz y

/-- **Theorem 11.1.7** in full: `(dF_Γ)_u` is Fredholm of index `μ(x) − μ(y)`.

A *predicate*, not a theorem: asserting it of arbitrary abstract data would be
false, and the objects of its proof (Sobolev spaces of sections, the
Cauchy–Riemann operator, paths of symplectic matrices) do not exist in
Mathlib. -/
def IsFredholmOfCZIndex : Prop := G.IsFredholmData ∧ G.HasCZIndex

end HomotopyData

/-- **The dimension count of Theorem 11.1.6.**

For a regular homotopy the kernel of `(dF_Γ)_u` — the tangent space to
`M_Γ(x,y)` at `u` — has dimension exactly `μ(x) − μ(y)`.  Everything in Theorem
11.1.6 that does not need the Banach manifold `P^{1,p}(x,y)` is proved here,
from Theorem 11.1.7 and regularity, exactly as in Chapter 8. -/
theorem finrank_ker_eq_cz_sub_cz {Da Db : Chapter8.FloerData E F} {G : HomotopyData Da Db}
    (_hfred : G.IsFredholmData) (hind : G.HasCZIndex) (hreg : G.IsRegular)
    {x : Da.Orbit} {y : Db.Orbit} (u : G.Sol x y) :
    (Module.finrank ℝ (LinearMap.ker (G.lin u : E →ₗ[ℝ] F)) : ℤ) = Da.cz x - Db.cz y := by
  rw [← Chapter8.fredholmIndex_eq_finrank_ker_of_surjective (hreg x y u)]
  exact hind x y u

section Genericity

variable {Da Db : Chapter8.FloerData E F} {Pert : Type*} [TopologicalSpace Pert]

/-- The book's `H_reg` for the parametrised equation: the compactly supported
perturbations `h` for which the homotopy `Γ(h) = (H + h, J)` is regular. -/
def regularSet (G : Pert → HomotopyData Da Db) : Set Pert := {h | (G h).IsRegular}

/-- **Theorem 11.1.6** as a predicate: the regular perturbations contain a
countable intersection of dense open subsets of a neighbourhood of `0` in
`C^∞_ε`.

Assumed.  The proof is the Sard–Smale theorem applied to the projection
`Z(x,y,J) → C^∞_ε`, whose Fredholm property comes from Theorem 11.1.7 and whose
submersion property is Proposition 11.1.8.  None of the spaces involved
exists in Mathlib. -/
def IsGenericallyRegular (G : Pert → HomotopyData Da Db) : Prop :=
  regularSet G ∈ residual Pert

/-- Unfolding of `IsGenericallyRegular`: it is exactly the book's phrasing, "a
countable intersection of dense open sets". -/
theorem isGenericallyRegular_iff (G : Pert → HomotopyData Da Db) :
    IsGenericallyRegular G ↔
      ∃ S : Set (Set Pert), (∀ t ∈ S, IsOpen t) ∧ (∀ t ∈ S, Dense t) ∧ S.Countable ∧
        ⋂₀ S ⊆ regularSet G :=
  mem_residual_iff

/-- **The way Theorem 11.1.6 is used**: arbitrarily close to a given homotopy
there is a regular one.  This is Baire's theorem, and it is proved; the space
`C^∞_ε` of §8.3 is a Banach space, hence a Baire space. -/
theorem dense_regularSet [BaireSpace Pert] (G : Pert → HomotopyData Da Db)
    (h : IsGenericallyRegular G) : Dense (regularSet G) :=
  dense_of_mem_residual h

end Genericity

section Gamma

variable {Pert : Type*} [NormedAddCommGroup Pert] [NormedSpace ℝ Pert]

/-- **Proposition 11.1.8** as a predicate: the operator

`Γ(Y, h) = (dF_Γ)_u(Y) + grad_u h : W^{1,p}(u⋆TW) × C^∞_ε → L^p(u⋆TW)`

is surjective.  Chapter 8's `gammaOp` is exactly this operator, and
`Chapter8.gammaOp_surjective_iff` already says that its surjectivity means that
the image of the linearised operator and the image of the perturbations together
span `L^p`.

Assumed: the book's proof is the contradiction argument recalled in
`lemma_11_1_9` below, which needs Hahn–Banach and the Riesz representation of
`(L^p)⋆` together with the geometric construction of Lemma 11.1.9. -/
def IsTransverseHomotopy (L : E →L[ℝ] F) (g : Pert →L[ℝ] F) : Prop :=
  Function.Surjective (Chapter8.gammaOp L g)

/-- **Lemma 11.1.9** in the form in which it is used.

The book's lemma says that a field `Z ∈ L^q(u⋆TW) ∩ C^∞` with
`⟨Z, grad_u h⟩ = 0` for every compactly supported perturbation `h` vanishes
identically; its proof constructs, near a point where `Z ≠ 0`, a perturbation
`h` with `dh(Z) > 0` on a small box, using that `(s,t) ↦ (u(s,t), s, t)` is an
embedding and that `Z` is transverse to it — a construction that has no
counterpart in Mathlib.

What that construction produces is exactly the *density* of the family of
perturbation gradients `grad_u h` in `L^p`, and from density the conclusion is
proved here: a continuous functional vanishing on a dense linear subspace
vanishes.  So the analytic content missing from this file is precisely
`DenseRange g`. -/
theorem lemma_11_1_9 {g : Pert →L[ℝ] F} (hg : DenseRange g) (Z : F →L[ℝ] ℝ)
    (hZ : ∀ h : Pert, Z (g h) = 0) : Z = 0 := by
  have key : (fun y => Z y) = (fun _ : F => (0 : ℝ)) :=
    hg.equalizer Z.continuous continuous_const (funext fun h => by simpa using hZ h)
  ext x
  simpa using congrFun key x

end Gamma

end Transversality

/-! ## §11.1.c The morphism `Φ_Γ`, and the algebra of the invariance proof

Everything from here on is proved.

The Floer complex `CF⋆(H, J)` is the free `R`-module on the `1`-periodic orbits,
graded by the Conley–Zehnder index `μ : Orbit → ℤ`, with differential
`∂ a = Σ_b n(a, b) · b`; the morphism `Φ_Γ` has the same shape, with the count
`n_Γ(x, y)` of elements of `M_Γ(x, y)` for `μ(x) = μ(y)`, and so does the
chain homotopy `S` of §11.3.  All three are instances of one construction,
`transfer`, and their three defining identities are instances of one computation
with a double sum. -/

section Algebra

variable {R : Type*} [CommRing R]

/-- The orbits of Conley–Zehnder index `k`. -/
abbrev OrbSet {O : Type*} (μ : O → ℤ) (k : ℤ) := {x : O // μ x = k}

/-- `CF_k`: the free `R`-module on the orbits of index `k` (§10.1), recorded by
the family of coefficients. -/
abbrev Chains (R : Type*) {O : Type*} (μ : O → ℤ) (k : ℤ) := OrbSet μ k → R

variable {Oa Ob Oc : Type*}

/-- **The map attached to a count matrix.**

Given a matrix of counts `n : Oa → Ob → R`, the induced map `CF_k → CF_l` sends
a generator `x` to `Σ_z n(x, z) · z`.  Taking `n` to be the count of Floer
trajectories gives the differential `∂` (`dLin`), taking it to be the count
`n_Γ` of parametrised trajectories gives `Φ_Γ`, and taking it to be the count
`m_Γ` of §11.3 gives the chain homotopy `S`. -/
def transfer [Fintype Oa] (μa : Oa → ℤ) (μb : Ob → ℤ) (n : Oa → Ob → R) (k l : ℤ) :
    Chains R μa k →ₗ[R] Chains R μb l where
  toFun c := fun z => ∑ x : OrbSet μa k, c x * n x.1 z.1
  map_add' c d := by
    funext z
    simp [add_mul, Finset.sum_add_distrib]
  map_smul' r c := by
    funext z
    simp [Finset.mul_sum, mul_assoc]

@[simp]
theorem transfer_apply [Fintype Oa] (μa : Oa → ℤ) (μb : Ob → ℤ) (n : Oa → Ob → R) (k l : ℤ)
    (c : Chains R μa k) (z : OrbSet μb l) :
    transfer μa μb n k l c z = ∑ x : OrbSet μa k, c x * n x.1 z.1 := rfl

/-- **The coefficient of a composite** is the matrix product: this one
computation is the whole of §11.1.c and §11.3. -/
theorem transfer_comp_apply [Fintype Oa] [Fintype Ob] (μa : Oa → ℤ) (μb : Ob → ℤ) (μc : Oc → ℤ)
    (n : Oa → Ob → R) (n' : Ob → Oc → R) (k l m : ℤ)
    (c : Chains R μa k) (z : OrbSet μc m) :
    transfer μb μc n' l m (transfer μa μb n k l c) z
      = ∑ x : OrbSet μa k, c x * ∑ y : OrbSet μb l, n x.1 y.1 * n' y.1 z.1 := by
  simp only [transfer_apply]
  have key : ∀ y : OrbSet μb l,
      (∑ x : OrbSet μa k, c x * n x.1 y.1) * n' y.1 z.1
        = ∑ x : OrbSet μa k, c x * (n x.1 y.1 * n' y.1 z.1) := by
    intro y
    rw [Finset.sum_mul]
    exact Finset.sum_congr rfl fun x _ => mul_assoc _ _ _
  simp only [key]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun x _ => ?_
  rw [Finset.mul_sum]

/-- If every matrix product vanishes, the composite is zero. -/
theorem transfer_comp_eq_zero [Fintype Oa] [Fintype Ob] {μa : Oa → ℤ} {μb : Ob → ℤ}
    {μc : Oc → ℤ} {n : Oa → Ob → R} {n' : Ob → Oc → R} {k l m : ℤ}
    (h : ∀ (x : OrbSet μa k) (z : OrbSet μc m),
      ∑ y : OrbSet μb l, n x.1 y.1 * n' y.1 z.1 = 0) :
    (transfer μb μc n' l m).comp (transfer μa μb n k l) = 0 := by
  ext c z
  simp only [LinearMap.comp_apply, LinearMap.zero_apply, Pi.zero_apply]
  rw [transfer_comp_apply]
  refine Finset.sum_eq_zero fun x _ => ?_
  rw [h x z, mul_zero]

/-- Two composites with equal matrix products are equal.  The two composites may
go through *different* intermediate sets of orbits and different degrees, which
is exactly the situation of the chain-map identity, where one side sums over the
orbits of `Ha` and the other over those of `Hb`. -/
theorem transfer_comp_eq [Fintype Oa] [Fintype Ob] [Fintype Oc] {Ob' : Type*} [Fintype Ob']
    {μa : Oa → ℤ} {μb : Ob → ℤ} {μb' : Ob' → ℤ} {μc : Oc → ℤ}
    {n1 : Oa → Ob → R} {n1' : Ob → Oc → R} {n2 : Oa → Ob' → R} {n2' : Ob' → Oc → R}
    {k l l' m : ℤ}
    (h : ∀ (x : OrbSet μa k) (z : OrbSet μc m),
      (∑ y : OrbSet μb l, n1 x.1 y.1 * n1' y.1 z.1)
        = ∑ y : OrbSet μb' l', n2 x.1 y.1 * n2' y.1 z.1) :
    (transfer μb μc n1' l m).comp (transfer μa μb n1 k l)
      = (transfer μb' μc n2' l' m).comp (transfer μa μb' n2 k l') := by
  ext c z
  simp only [LinearMap.comp_apply]
  rw [transfer_comp_apply, transfer_comp_apply]
  exact Finset.sum_congr rfl fun x _ => by rw [h x z]

/-- **The Floer differential** `∂ : CF_k → CF_l` attached to a count function
(§10.1); `l` is `k − 1` in all uses. -/
def dLin {O : Type*} [Fintype O] (μ : O → ℤ) (cnt : O → O → R) (k l : ℤ) :
    Chains R μ k →ₗ[R] Chains R μ l :=
  transfer μ μ cnt k l

/-- **The broken-trajectory hypothesis** for the Floer complex, the analogue of
`MorseFloer.Chapter3.BrokenPairs`: for `μ(x) = μ(z) + 2` the once-broken
trajectories from `x` to `z` cancel.  It is the conclusion of the compactness
and gluing theorems of Chapter 9, and it is what makes `∂ ∘ ∂ = 0`. -/
def BrokenPairs {O : Type*} [Fintype O] (μ : O → ℤ) (cnt : O → O → R) : Prop :=
  ∀ (k : ℤ) (x : OrbSet μ (k + 2)) (z : OrbSet μ k),
    ∑ y : OrbSet μ (k + 1), cnt x.1 y.1 * cnt y.1 z.1 = 0

/-- `∂ ∘ ∂ = 0`, proved from the broken-trajectory hypothesis. -/
theorem dLin_comp_dLin {O : Type*} [Fintype O] {μ : O → ℤ} {cnt : O → O → R}
    (h : BrokenPairs μ cnt) {k l m : ℤ} (hk : k = l + 1) (hm : m = l + 2) :
    (dLin μ cnt k l).comp (dLin μ cnt m k) = 0 := by
  subst hk
  subst hm
  exact transfer_comp_eq_zero (h l)

/-! ### The morphism `Φ_Γ` is a chain map

For `x` of index `k + 1` and `z` of index `k`, the boundary of the compact
`1`-manifold `M_Γ(x,z) ∪ Π_Γ(x,z)` of Theorem 11.1.15 is `Π_Γ(x,z)`, the set of
once-broken configurations; it has an even number of points, which modulo `2` is
the identity below.  Over an arbitrary ring it is the statement that the two
ways of breaking give the same count. -/

/-- **The hypothesis supplied by Theorem 11.1.15**: for `μ(x) = μ(z) + 1`,

`Σ_{y'} n_a(x, y') n_Γ(y', z) = Σ_{y} n_Γ(x, y) n_b(y, z)`,

the left sum over the orbits `y'` of `Ha` of index `μ(z)` and the right one over
the orbits `y` of `Hb` of index `μ(x)`. -/
def ChainMapPairs [Fintype Oa] [Fintype Ob] (μa : Oa → ℤ) (μb : Ob → ℤ)
    (cnta : Oa → Oa → R) (cntb : Ob → Ob → R) (nG : Oa → Ob → R) : Prop :=
  ∀ (k : ℤ) (x : OrbSet μa (k + 1)) (z : OrbSet μb k),
    (∑ y : OrbSet μa k, cnta x.1 y.1 * nG y.1 z.1)
      = ∑ y : OrbSet μb (k + 1), nG x.1 y.1 * cntb y.1 z.1

/-- **`Φ_Γ` is a morphism of complexes** (§11.1.c):
`Φ_Γ ∘ ∂_{(Ha,Ja)} = ∂_{(Hb,Jb)} ∘ Φ_Γ`.

Proved from `ChainMapPairs`, which is the geometric input. -/
theorem transfer_chainMap [Fintype Oa] [Fintype Ob] {μa : Oa → ℤ} {μb : Ob → ℤ}
    {cnta : Oa → Oa → R} {cntb : Ob → Ob → R} {nG : Oa → Ob → R}
    (h : ChainMapPairs μa μb cnta cntb nG) {k l : ℤ} (hk : k = l + 1) :
    (transfer μa μb nG l l).comp (dLin μa cnta k l)
      = (dLin μb cntb k l).comp (transfer μa μb nG k k) := by
  subst hk
  exact transfer_comp_eq (h l)

/-! ### Proposition 11.1.14: the stationary homotopy gives the identity -/

/-- The count matrix of the stationary homotopy: for `Γ = Id` one has
`M_Γ(x,y) = M_{(Ha,Ja)}(x,y)`, which for `μ(x) = μ(y)` is empty unless `x = y`
and is the single constant trajectory when `x = y` (Remark 9.1.5). -/
def idCount (R : Type*) [CommRing R] (O : Type*) [DecidableEq O] : O → O → R :=
  fun x y => if x = y then 1 else 0

/-- **Proposition 11.1.14.**  For the stationary homotopy, `Φ_Γ` is the
identity. -/
theorem transfer_idCount {O : Type*} [Fintype O] [DecidableEq O] (μ : O → ℤ) (k : ℤ) :
    transfer μ μ (idCount R O) k k = LinearMap.id := by
  ext c z
  show (∑ x : OrbSet μ k, c x * idCount R O x.1 z.1) = c z
  have key : ∀ b : OrbSet μ k, b ≠ z → c b * idCount R O b.1 z.1 = 0 := by
    intro b hb
    have hbz : b.1 ≠ z.1 := fun hh => hb (Subtype.ext hh)
    simp [idCount, hbz]
  rw [Finset.sum_eq_single z (fun b _ hb => key b hb) fun hh =>
    absurd (Finset.mem_univ z) hh]
  simp [idCount]

/-! ### §11.5: the concatenated homotopy

Proposition 11.5.3 says that for `ρ` large the parametrised trajectories of the
concatenated homotopy `Γ_ρ` are in bijection with the composable pairs, so that
`n_{Γ_ρ}(x, z) = Σ_y n_{Γ'}(x, y) n_{Γ''}(y, z)`.  That matrix product is the
count matrix `concat` below, and the chain-level consequence
`Φ_{Γ_ρ} = Φ_{Γ''} ∘ Φ_{Γ'}` is then proved. -/

/-- The matrix product of two count matrices, in the only degree in which it is
used: `concat(x, z) = Σ_{μ(y) = μ(x)} n'(x, y) n''(y, z)`. -/
def concat [Fintype Ob] (μa : Oa → ℤ) (μb : Ob → ℤ) (n' : Oa → Ob → R) (n'' : Ob → Oc → R) :
    Oa → Oc → R :=
  fun x z => ∑ y : OrbSet μb (μa x), n' x y.1 * n'' y.1 z

theorem concat_apply [Fintype Ob] (μa : Oa → ℤ) (μb : Ob → ℤ) (n' : Oa → Ob → R)
    (n'' : Ob → Oc → R) {k : ℤ} (x : OrbSet μa k) (z : Oc) :
    concat μa μb n' n'' x.1 z = ∑ y : OrbSet μb k, n' x.1 y.1 * n'' y.1 z := by
  obtain ⟨x, hx⟩ := x
  subst hx
  rfl

/-- **Proposition 11.5.3 at the chain level**: the morphism of the concatenated
homotopy is the composite of the two morphisms. -/
theorem transfer_comp_concat [Fintype Oa] [Fintype Ob] [Fintype Oc]
    (μa : Oa → ℤ) (μb : Ob → ℤ) (μc : Oc → ℤ) (n' : Oa → Ob → R) (n'' : Ob → Oc → R)
    (k : ℤ) :
    (transfer μb μc n'' k k).comp (transfer μa μb n' k k)
      = transfer μa μc (concat μa μb n' n'') k k := by
  ext c z
  simp only [LinearMap.comp_apply]
  rw [transfer_comp_apply, transfer_apply]
  exact Finset.sum_congr rfl fun x _ => by rw [concat_apply]

/-! ### §11.3: the chain homotopy

For a homotopy of homotopies `(Γ_λ)` from `Γ₀` to `Γ₁`, Theorem 11.3.11 makes
`M_Γ(x,z) ∪ Π_Γ(x,z)` a compact `1`-manifold whose boundary is
`Π_Γ(x,z) ∪ ({0} × M_{Γ₀}(x,z)) ∪ ({1} × M_{Γ₁}(x,z))`, so that the total number
of points of that boundary is even.  Modulo `2` this is the identity below,
which says that `S`, the count of the `1`-parameter family, is a chain homotopy
between `Φ_{Γ₀}` and `Φ_{Γ₁}`. -/

/-- **The hypothesis supplied by Theorem 11.3.11**: for `μ(x) = μ(z)`,

`n_{Γ₁}(x,z) − n_{Γ₀}(x,z)
  = Σ_{y'} n_a(x, y') m(y', z) + Σ_{y} m(x, y) n_b(y, z)`,

the first sum over the orbits `y'` of `Ha` of index `μ(x) − 1` and the second
over the orbits `y` of `Hb` of index `μ(x) + 1`. -/
def ChainHomotopyPairs [Fintype Oa] [Fintype Ob] (μa : Oa → ℤ) (μb : Ob → ℤ)
    (cnta : Oa → Oa → R) (cntb : Ob → Ob → R) (n0 n1 m : Oa → Ob → R) : Prop :=
  ∀ (k : ℤ) (x : OrbSet μa k) (z : OrbSet μb k),
    n1 x.1 z.1 - n0 x.1 z.1
      = (∑ y : OrbSet μa (k - 1), cnta x.1 y.1 * m y.1 z.1)
        + ∑ y : OrbSet μb (k + 1), m x.1 y.1 * cntb y.1 z.1

/-- **Proposition 11.2.8 at the chain level**: `S` is a chain homotopy,

`Φ_{Γ₁} − Φ_{Γ₀} = S ∘ ∂_{(Ha,Ja)} + ∂_{(Hb,Jb)} ∘ S`,

with `S : CF_k(Ha, Ja) → CF_{k+1}(Hb, Jb)` the map attached to the count `m` of
the `1`-parameter family.  Proved from `ChainHomotopyPairs`. -/
theorem transfer_homotopy [Fintype Oa] [Fintype Ob] {μa : Oa → ℤ} {μb : Ob → ℤ}
    {cnta : Oa → Oa → R} {cntb : Ob → Ob → R} {n0 n1 m : Oa → Ob → R}
    (h : ChainHomotopyPairs μa μb cnta cntb n0 n1 m) (k : ℤ) (c : Chains R μa k) :
    transfer μa μb n1 k k c - transfer μa μb n0 k k c
      = transfer μa μb m (k - 1) k (dLin μa cnta k (k - 1) c)
        + dLin μb cntb (k + 1) k (transfer μa μb m k (k + 1) c) := by
  funext z
  simp only [Pi.sub_apply, Pi.add_apply, transfer_apply]
  rw [show (dLin μa cnta k (k - 1)) = transfer μa μa cnta k (k - 1) from rfl,
    show (dLin μb cntb (k + 1) k) = transfer μb μb cntb (k + 1) k from rfl]
  rw [transfer_comp_apply, transfer_comp_apply, ← Finset.sum_sub_distrib,
    ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun x _ => ?_
  rw [← mul_sub, ← mul_add, h k x z]

end Algebra

/-! ## The homology of a complex, and the invariance argument

Nothing in this section is specific to Floer theory: it is the homological
algebra that turns the three identities above into the isomorphism of §11.6.
The pieces mirror `MorseFloer.Chapter3.chainMap_of_coneDiff_comp` and
`MorseFloer.Chapter3.sub_mem_range_of_chainHomotopy`, which are the same two
steps for the Morse complex; what is added here is the passage to the quotient,
i.e. the induced maps on homology and their functoriality. -/

section Homology

variable {R : Type*} [CommRing R]
variable {A₀ A A₁ B₀ B B₁ C₀ C C₁ : Type*}
  [AddCommGroup A₀] [Module R A₀] [AddCommGroup A] [Module R A]
  [AddCommGroup A₁] [Module R A₁]
  [AddCommGroup B₀] [Module R B₀] [AddCommGroup B] [Module R B]
  [AddCommGroup B₁] [Module R B₁]
  [AddCommGroup C₀] [Module R C₀] [AddCommGroup C] [Module R C]
  [AddCommGroup C₁] [Module R C₁]

/-- **The homology of a two-term situation** `A₀ --f--> A --g--> A₁`:
`Ker g / (Im f ∩ Ker g)`.

When `g ∘ f = 0` — which is `dLin_comp_dLin` in the Floer case — the
intersection is all of `Im f` and this is the book's `Ker ∂ / Im ∂`; stating it
with the intersection makes the definition legitimate without that hypothesis,
which keeps the functoriality lemmas below free of side conditions. -/
abbrev Hgy (f : A₀ →ₗ[R] A) (g : A →ₗ[R] A₁) : Type _ :=
  (LinearMap.ker g) ⧸ Submodule.comap (LinearMap.ker g).subtype (LinearMap.range f)

/-- The homology class of a cycle. -/
def Hgy.mk (f : A₀ →ₗ[R] A) (g : A →ₗ[R] A₁) : (LinearMap.ker g) →ₗ[R] Hgy f g :=
  Submodule.mkQ _

theorem Hgy.mk_eq (f : A₀ →ₗ[R] A) (g : A →ₗ[R] A₁) (x : LinearMap.ker g) :
    Hgy.mk f g x = Submodule.Quotient.mk x := rfl

theorem Hgy.mk_surjective (f : A₀ →ₗ[R] A) (g : A →ₗ[R] A₁) :
    Function.Surjective (Hgy.mk f g) := by
  intro c
  obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ c
  exact ⟨x, rfl⟩

/-- Two cycles have the same class exactly when they differ by a boundary. -/
theorem Hgy.mk_eq_mk_iff (f : A₀ →ₗ[R] A) (g : A →ₗ[R] A₁) (a b : LinearMap.ker g) :
    Hgy.mk f g a = Hgy.mk f g b ↔ (a : A) - (b : A) ∈ LinearMap.range f := by
  rw [Hgy.mk_eq, Hgy.mk_eq, Submodule.Quotient.eq]
  exact Iff.rfl

/-- A chain map sends cycles to cycles. -/
theorem Hgy.mapsTo_ker {g : A →ₗ[R] A₁} {g' : B →ₗ[R] B₁} {φ : A →ₗ[R] B} {φ₁ : A₁ →ₗ[R] B₁}
    (hg : φ₁.comp g = g'.comp φ) (x : A) (hx : x ∈ LinearMap.ker g) :
    φ x ∈ LinearMap.ker g' := by
  have h := LinearMap.congr_fun hg x
  simp only [LinearMap.comp_apply] at h
  rw [LinearMap.mem_ker] at hx ⊢
  rw [← h, hx, map_zero]

/-- **A chain map induces a map on homology.**

This is the first thing the chapter needs of `Φ_Γ` once it is known to be a
morphism of complexes. -/
def Hgy.map {f : A₀ →ₗ[R] A} {g : A →ₗ[R] A₁} {f' : B₀ →ₗ[R] B} {g' : B →ₗ[R] B₁}
    {φ₀ : A₀ →ₗ[R] B₀} {φ : A →ₗ[R] B} {φ₁ : A₁ →ₗ[R] B₁}
    (hf : φ.comp f = f'.comp φ₀) (hg : φ₁.comp g = g'.comp φ) :
    Hgy f g →ₗ[R] Hgy f' g' :=
  Submodule.mapQ _ _ (φ.restrict (Hgy.mapsTo_ker hg)) (by
    intro y hy
    obtain ⟨x, hxk⟩ := y
    have hx : x ∈ LinearMap.range f := hy
    obtain ⟨a, rfl⟩ := hx
    show φ (f a) ∈ LinearMap.range f'
    refine ⟨φ₀ a, ?_⟩
    have hfa := LinearMap.congr_fun hf a
    simp only [LinearMap.comp_apply] at hfa
    exact hfa.symm)

@[simp]
theorem Hgy.map_mk {f : A₀ →ₗ[R] A} {g : A →ₗ[R] A₁} {f' : B₀ →ₗ[R] B} {g' : B →ₗ[R] B₁}
    {φ₀ : A₀ →ₗ[R] B₀} {φ : A →ₗ[R] B} {φ₁ : A₁ →ₗ[R] B₁}
    (hf : φ.comp f = f'.comp φ₀) (hg : φ₁.comp g = g'.comp φ) (x : LinearMap.ker g) :
    Hgy.map hf hg (Hgy.mk f g x) = Hgy.mk f' g' ⟨φ x, Hgy.mapsTo_ker hg x x.2⟩ := rfl

/-- Chain maps compose. -/
theorem chainMap_comp {f : A₀ →ₗ[R] A} {f' : B₀ →ₗ[R] B} {f'' : C₀ →ₗ[R] C}
    {φ₀ : A₀ →ₗ[R] B₀} {φ : A →ₗ[R] B} {ψ₀ : B₀ →ₗ[R] C₀} {ψ : B →ₗ[R] C}
    (hf : φ.comp f = f'.comp φ₀) (hf' : ψ.comp f' = f''.comp ψ₀) :
    (ψ.comp φ).comp f = f''.comp (ψ₀.comp φ₀) := by
  ext a
  simp only [LinearMap.comp_apply]
  have h1 := LinearMap.congr_fun hf a
  have h2 := LinearMap.congr_fun hf' (φ₀ a)
  simp only [LinearMap.comp_apply] at h1 h2
  rw [h1, h2]

/-- **Functoriality**: the map induced by a composite is the composite of the
induced maps. -/
theorem Hgy.map_comp {f : A₀ →ₗ[R] A} {g : A →ₗ[R] A₁} {f' : B₀ →ₗ[R] B} {g' : B →ₗ[R] B₁}
    {f'' : C₀ →ₗ[R] C} {g'' : C →ₗ[R] C₁}
    {φ₀ : A₀ →ₗ[R] B₀} {φ : A →ₗ[R] B} {φ₁ : A₁ →ₗ[R] B₁}
    {ψ₀ : B₀ →ₗ[R] C₀} {ψ : B →ₗ[R] C} {ψ₁ : B₁ →ₗ[R] C₁}
    (hf : φ.comp f = f'.comp φ₀) (hg : φ₁.comp g = g'.comp φ)
    (hf' : ψ.comp f' = f''.comp ψ₀) (hg' : ψ₁.comp g' = g''.comp ψ)
    (hf'' : (ψ.comp φ).comp f = f''.comp (ψ₀.comp φ₀))
    (hg'' : (ψ₁.comp φ₁).comp g = g''.comp (ψ.comp φ)) :
    (Hgy.map hf' hg').comp (Hgy.map hf hg) = Hgy.map hf'' hg'' := by
  refine LinearMap.ext fun c => ?_
  obtain ⟨x, rfl⟩ := Hgy.mk_surjective f g c
  rfl

/-- The identity chain map induces the identity on homology. -/
theorem Hgy.map_id {f : A₀ →ₗ[R] A} {g : A →ₗ[R] A₁}
    (hf : (LinearMap.id : A →ₗ[R] A).comp f = f.comp (LinearMap.id : A₀ →ₗ[R] A₀))
    (hg : (LinearMap.id : A₁ →ₗ[R] A₁).comp g = g.comp (LinearMap.id : A →ₗ[R] A)) :
    Hgy.map hf hg = LinearMap.id := by
  refine LinearMap.ext fun c => ?_
  obtain ⟨x, rfl⟩ := Hgy.mk_surjective f g c
  rfl

/-- **Chain-homotopic maps agree on homology.**

If `φ − ψ = f' ∘ S + T ∘ g` then `φ` and `ψ` induce the same map, because on a
cycle `x` the difference is `f' (S x)`, a boundary.  This is the passage to the
quotient of `MorseFloer.Chapter3.sub_mem_range_of_chainHomotopy`, and it is what
Proposition 11.2.8 needs. -/
theorem Hgy.map_eq_of_homotopy {f : A₀ →ₗ[R] A} {g : A →ₗ[R] A₁} {f' : B₀ →ₗ[R] B}
    {g' : B →ₗ[R] B₁}
    {φ₀ : A₀ →ₗ[R] B₀} {φ : A →ₗ[R] B} {φ₁ : A₁ →ₗ[R] B₁}
    {ψ₀ : A₀ →ₗ[R] B₀} {ψ : A →ₗ[R] B} {ψ₁ : A₁ →ₗ[R] B₁}
    (hφf : φ.comp f = f'.comp φ₀) (hφg : φ₁.comp g = g'.comp φ)
    (hψf : ψ.comp f = f'.comp ψ₀) (hψg : ψ₁.comp g = g'.comp ψ)
    (S : A →ₗ[R] B₀) (T : A₁ →ₗ[R] B)
    (hom : ∀ x : A, φ x - ψ x = f' (S x) + T (g x)) :
    Hgy.map hφf hφg = Hgy.map hψf hψg := by
  refine LinearMap.ext fun c => ?_
  obtain ⟨x, rfl⟩ := Hgy.mk_surjective f g c
  simp only [Hgy.map_mk]
  rw [Hgy.mk_eq_mk_iff]
  show φ (x : A) - ψ (x : A) ∈ LinearMap.range f'
  rw [hom (x : A), LinearMap.mem_ker.mp x.2, map_zero, add_zero]
  exact ⟨S (x : A), rfl⟩

/-- **The step that makes `Φ_Γ` an isomorphism.**

If the composite `ψ ∘ φ` of two chain maps is chain homotopic to the identity,
then the induced maps on homology compose to the identity.  Applying this in
both directions — which is what Propositions 11.2.8, 11.2.9 and 11.1.14 give,
with `Γ` the stationary homotopy — makes the two induced maps mutually inverse.
-/
theorem Hgy.map_comp_map_eq_id {f : A₀ →ₗ[R] A} {g : A →ₗ[R] A₁} {f' : B₀ →ₗ[R] B}
    {g' : B →ₗ[R] B₁}
    {φ₀ : A₀ →ₗ[R] B₀} {φ : A →ₗ[R] B} {φ₁ : A₁ →ₗ[R] B₁}
    {ψ₀ : B₀ →ₗ[R] A₀} {ψ : B →ₗ[R] A} {ψ₁ : B₁ →ₗ[R] A₁}
    (hφf : φ.comp f = f'.comp φ₀) (hφg : φ₁.comp g = g'.comp φ)
    (hψf : ψ.comp f' = f.comp ψ₀) (hψg : ψ₁.comp g' = g.comp ψ)
    (S : A →ₗ[R] A₀) (T : A₁ →ₗ[R] A)
    (hom : ∀ x : A, ψ (φ x) - x = f (S x) + T (g x)) :
    (Hgy.map hψf hψg).comp (Hgy.map hφf hφg) = LinearMap.id := by
  refine LinearMap.ext fun c => ?_
  obtain ⟨x, rfl⟩ := Hgy.mk_surjective f g c
  simp only [LinearMap.comp_apply, LinearMap.id_apply, Hgy.map_mk]
  rw [Hgy.mk_eq_mk_iff]
  show ψ (φ (x : A)) - (x : A) ∈ LinearMap.range f
  rw [hom (x : A), LinearMap.mem_ker.mp x.2, map_zero, add_zero]
  exact ⟨S (x : A), rfl⟩

/-- Two induced maps that compose to the identity in both orders make the
homologies isomorphic. -/
def Hgy.equivOfCompEqId {M N : Type*} [AddCommGroup M] [Module R M]
    [AddCommGroup N] [Module R N] (u : M →ₗ[R] N) (v : N →ₗ[R] M)
    (h1 : v.comp u = LinearMap.id) (h2 : u.comp v = LinearMap.id) : M ≃ₗ[R] N :=
  LinearEquiv.ofLinear u v h2 h1

end Homology

/-! ## §11.6 Conclusion: the invariance of Floer homology

Assembling the pieces.  `HF_k(H, J)` is the homology of the complex
`CF_{k+1} → CF_k → CF_{k−1}`, a chain map `Φ_Γ` induces a map on it, and the
chapter's two propositions say that the two morphisms attached to a homotopy and
to a homotopy in the opposite direction compose, in homology, to the morphism of
the stationary homotopy, which is the identity.  Hence `Φ_Γ` is an isomorphism
and `HF_k(Ha, Ja) ≅ HF_k(Hb, Jb)`. -/

section Invariance

variable {R : Type*} [CommRing R] {Oa Ob : Type*} [Fintype Oa] [Fintype Ob]

/-- **Floer homology `HF_k(H, J)`** (§10.1), as the homology of the complex of
`1`-periodic orbits graded by the Conley–Zehnder index. -/
abbrev floerHomology (μ : Oa → ℤ) (cnt : Oa → Oa → R) (k : ℤ) :=
  Hgy (dLin μ cnt (k + 1) k) (dLin μ cnt k (k - 1))

/-- **The morphism induced by `Φ_Γ` on Floer homology** (§11.1.c together with
the second step of the plan of the chapter). -/
def homologyMap {μa : Oa → ℤ} {μb : Ob → ℤ} {cnta : Oa → Oa → R} {cntb : Ob → Ob → R}
    {nG : Oa → Ob → R} (h : ChainMapPairs μa μb cnta cntb nG) (k : ℤ) :
    floerHomology μa cnta k →ₗ[R] floerHomology μb cntb k :=
  Hgy.map (transfer_chainMap h (rfl : k + 1 = k + 1))
    (transfer_chainMap h (by ring : k = (k - 1) + 1))

/-- **The invariance theorem, §11.6.**

Let `Γ'` be a regular homotopy from `(Ha, Ja)` to `(Hb, Jb)` and `Γ''` one from
`(Hb, Jb)` back to `(Ha, Ja)`.  Suppose that in each direction the concatenated
homotopy is chain homotopic to the stationary one — which is what Proposition
11.2.9 (the concatenation induces the composite, `transfer_comp_concat`),
Proposition 11.2.8 (any two homotopies are chain homotopic, `transfer_homotopy`)
and Proposition 11.1.14 (`transfer_idCount`) supply.  Then `Φ_{Γ'}` is an
isomorphism on homology:

`HF_k(Ha, Ja) ≅ HF_k(Hb, Jb)`.

Every step of this chain is proved; only the two geometric hypotheses
`ChainMapPairs` and `ChainHomotopyPairs`, which record the boundary counts of
the compact `1`-manifolds of Theorems 11.1.15 and 11.3.11, are assumed. -/
noncomputable def floerHomologyEquiv [DecidableEq Oa] [DecidableEq Ob]
    {μa : Oa → ℤ} {μb : Ob → ℤ} {cnta : Oa → Oa → R} {cntb : Ob → Ob → R}
    {n' : Oa → Ob → R} {n'' : Ob → Oa → R} {ma : Oa → Oa → R} {mb : Ob → Ob → R}
    (h' : ChainMapPairs μa μb cnta cntb n') (h'' : ChainMapPairs μb μa cntb cnta n'')
    (hba : ChainHomotopyPairs μa μa cnta cnta (idCount R Oa) (concat μa μb n' n'') ma)
    (hab : ChainHomotopyPairs μb μb cntb cntb (idCount R Ob) (concat μb μa n'' n') mb)
    (k : ℤ) : floerHomology μa cnta k ≃ₗ[R] floerHomology μb cntb k := by
  refine Hgy.equivOfCompEqId (homologyMap h' k) (homologyMap h'' k) ?_ ?_
  · refine Hgy.map_comp_map_eq_id _ _ _ _
      (transfer μa μa ma k (k + 1)) (transfer μa μa ma (k - 1) k) fun x => ?_
    have key := transfer_homotopy hba k x
    rw [transfer_idCount] at key
    have hcomp : transfer μa μa (concat μa μb n' n'') k k x
        = transfer μb μa n'' k k (transfer μa μb n' k k x) := by
      rw [← transfer_comp_concat]
      rfl
    rw [hcomp] at key
    rw [key]
    exact add_comm _ _
  · refine Hgy.map_comp_map_eq_id _ _ _ _
      (transfer μb μb mb k (k + 1)) (transfer μb μb mb (k - 1) k) fun x => ?_
    have key := transfer_homotopy hab k x
    rw [transfer_idCount] at key
    have hcomp : transfer μb μb (concat μb μa n'' n') k k x
        = transfer μa μb n' k k (transfer μb μa n'' k k x) := by
      rw [← transfer_comp_concat]
      rfl
    rw [hcomp] at key
    rw [key]
    exact add_comm _ _

end Invariance

end Chapter11
end MorseFloer
